apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dsamist
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: dsamist
    server: https://kubernetes.default.svc
    ##uncomment this part if you have to add another argocd project.
  ## - namespace: microservices
  ##   server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
