apiVersion: v2
name: argo
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.19

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.16.0

home: https://bitbucket.org/irembo/irembo-rest.git
maintainers:
  - email: devops@irembo.com
    name: devops
sources:
  - https://bitbucket.org/irembo/irembo-rest.git

dependencies:
- name: argo-cd
  version: 3.33.5
  repository: https://argoproj.github.io/argo-helm
  condition: argo-cd.enabled
  tags:
  - argo
  - cd
- name: argocd-image-updater
  version: 0.6.2
  repository: https://argoproj.github.io/argo-helm
  condition: argocd-image-updater.enabled
  tags:
  - argo
  - cd
  - image
  - updater
- name: argocd-notifications
  version: 1.8.0
  repository: https://argoproj.github.io/argo-helm
  condition: argocd-notifications.enabled
  tags:
    - argo
    - cd
    - notifications
