# name: working with artifacts #defines the name of the workflow

# on: [pull_request]   #the action that can trigger this workflow.

# env:
#   ARTIFACT_NAME: myartifact #create an environment variable that is needed later in this workflow

# jobs:                       #define thejobs to be done
#   upload-artifacts:         #one of the jobs
#     name: upload-artifacts  #jon name
#     runs-on: ubuntu-latest  #platform to run job on
#     steps:                    #steps define the different actions under a job
#       - name: checkout step   #name of a step
#         uses: actions/checkout@v2 #action to be performed by the step

#       - name: upload step
#         uses: actions/upload-artifact@v2      #an action to upload content
#         with:                                 #using a with indicates that the step requires some parameters to run
#           name: $ {{ env.ARTIFACT_NAME }}     # use the parameter defined earlier.
#           path: .                             #paths containing contents to upload. This will be zipped

