name: print date

on: [pull_request]

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: print ubuntu date
        run: date

  job2:
    name: second job
    runs-on: windows-latest
    steps:
      - name: print windows date
        run: Get-Date

  job3:
    name: third job
    runs-on: macos-latest
    steps:
      - name: print mac date
        run: date

  job4:
    needs: [job1, job2, job3]
    name: fourth job
    runs-on: ubuntu-latest
    steps:
      - name: print another ubuntu date
        run: date
